<?php

namespace Database\Seeders;

use App\Models\Tax;
use App\Models\Unit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use JeroenNoten\LaravelAdminLte\View\Components\Widget\Card;

class MasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //prefixes
        DB::table('prefixes')->insert([
            [
                'name_th' => 'นาย',
                'name_en' => 'Mr.',
                'slug' => 'นาย',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'นาง',
                'name_en' => 'Mrs.',
                'slug' => 'นาง',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'นางสาว',
                'name_en' => 'Miss',
                'slug' => 'นางสาว',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('type_businesses')->insert([

            [
                'name_th' => 'บุคคลธรรมดา',
                'name_en' => 'Ordinary Person',
                'publish' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'นิติบุคคล',
                'name_en' => 'Juristic Person',
                'publish' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('category_businesses')->insert([

            [
                'name_th' => 'บุคคลธรรมดา',
                'name_en' => 'Human',
                'publish' => '1',
                'type_business_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ห้างหุ้นส่วนสามัญ',
                'name_en' => 'Ordinary Partnership',
                'publish' => '1',
                'type_business_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ร้านค้า',
                'name_en' => 'Shop',
                'publish' => '1',
                'type_business_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'คณะบุคคล',
                'name_en' => 'Body of Persons',
                'publish' => '1',
                'type_business_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'บริษัทจำกัด',
                'name_en' => 'Company Limited',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'บริษัทมหาชนจำกัด',
                'name_en' => 'Public Company Limited',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ห้างหุ้นส่วนจำกัด',
                'name_en' => 'Limited Partnership',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'มูลนิธิ',
                'name_en' => 'Foundation',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'สมาคม',
                'name_en' => 'Association',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'กิจการร่วมค้า',
                'name_en' => 'Join Venture',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'อื่นๆ',
                'name_en' => 'Others',
                'publish' => '1',
                'type_business_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        //Company
        DB::table('companies')->insert([
            [
                'company_code' => 'CO001',
                'name_th' => 'บริษัท A',
                'name_en' => 'A Company Ltd.,',
                'tax_number' => '1533021164475',
                'publish' => '1',
                'phone' => '0321546842',
                'type_business_id' => '2',
                'category_business_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // Company Address
        DB::table('company_addresses')->insert([
            [
                'detail_th' => '32/1 ถนนจรัญสนิทวงศ์',
                'sub_district_th' => 'บางอ้อ',
                'district_th' => 'บางพลัด',
                'province_th' => 'กรุงเทพมหานคร',
                'detail_en' => '32/1 Charansanitwong Rd.',
                'sub_district_en' => 'Bang O',
                'district_en' => 'Bang Phlat',
                'province_en' => 'Bangkok',
                'postcode' => '10700',
                'company_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // DB::table('setting_doc_types')->insert([
        //     [
        //         'header' => 'QO',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '1',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'TDN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '2',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'IV',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '3',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'IVT',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '4',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'DN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '5',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'RE',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '6',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'RT',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '7',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'TIV',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '8',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'CN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '9',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'CNT',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '10',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'BN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '11',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'DBN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '12',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'DBNT',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '13',
        //         'account_type' => '1',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'PO',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '14',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'POA',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '15',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'PR',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '16',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'EXP',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '17',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'CNX',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '18',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'CPN',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '19',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'header' => 'PA',
        //         'special_characters' => '-',
        //         'year_type' => '1',
        //         'month_type' => '1',
        //         'date_type' => '1',
        //         'length_number_doc' => '5',
        //         'doc_type' => '20',
        //         'account_type' => '2',
        //         'remark' => '',
        //         'company_id' => '1',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        // ]);
        // DB::table('setting_due_dates')->insert([
        //     [
        //         'doc_type' => 1,
        //         'account_type' => 1,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'doc_type' => 2,
        //         'account_type' => 1,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'doc_type' => 3,
        //         'account_type' => 1,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'doc_type' => 4,
        //         'account_type' => 2,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'doc_type' => 5,
        //         'account_type' => 2,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        //     [
        //         'doc_type' => 6,
        //         'account_type' => 2,
        //         'format_due_date' => 1,
        //         'length_due_date' => 1,
        //         'company_id' => 1,
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ],
        // ]);

        //banks
        DB::table('banks')->insert([
            [
                'name_th' => 'ธ.กรุงเทพ',
                'name_en' => 'BBL',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.กสิกรไทย',
                'name_en' => 'KBANK',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ไทยพานิชญ์',
                'name_en' => 'SCB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เอสเอ็มอี',
                'name_en' => 'SME',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.กรุงไทย',
                'name_en' => 'KTB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.กรุงศรี',
                'name_en' => 'BAY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เกียรตินาคินภัทร',
                'name_en' => 'KKP',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ซีไอเอ็มบีที',
                'name_en' => 'CIMBT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ทหารไทยธนชาต',
                'name_en' => 'TTB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ทิสโก้',
                'name_en' => 'TISCO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ไทยเครดิต',
                'name_en' => 'TCR',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ธนชาต',
                'name_en' => 'TBANK',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ธกส',
                'name_en' => 'BAAC',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ธสน.',
                'name_en' => 'EXIM',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ยูโอบี',
                'name_en' => 'UOB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.แลนด์ แอนด์ เฮาส์',
                'name_en' => 'LHBANK',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.สแตนดาร์ด',
                'name_en' => 'SCBT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ออมสิน',
                'name_en' => 'GSB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name_th' => 'ธ.อิสลาม',
                'name_en' => 'ISBT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ไอซีบีซี',
                'name_en' => 'ICBCT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เจพีมอร์แกน',
                'name_en' => 'JPMCB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ซิตี้แบงค์',
                'name_en' => 'CITI',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ซูมิโตโม',
                'name_en' => 'SMBC',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ดอยซ์แบงก์',
                'name_en' => 'DBBK',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.บีเอ็นพี',
                'name_en' => 'BNPP',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.มิซูโฮ',
                'name_en' => 'MIZUHO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เมกะสากล',
                'name_en' => 'Mega',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.แห่งประเทศจีน',
                'name_en' => 'BOC',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.แห่งอเมริกา',
                'name_en' => 'BofA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เอสเอ็มทีบี',
                'name_en' => 'SMTB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.อาร์ เอช บี',
                'name_en' => 'RHB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.ไอโอบี',
                'name_en' => 'Indian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เอชเอสบีซี',
                'name_en' => 'HSBC',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.เอเอ็นแซด',
                'name_en' => 'ANZ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.โอเวอร์ซี',
                'name_en' => 'OCBC',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_th' => 'ธ.อาคารสงเคราะห์',
                'name_en' => 'GHB',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        /**
         * unit
         */
        $this->call(UnitSeeder::class);
        // $units = [
        //     [
        //         "id" => 1,
        //         "code" => "box",
        //         "type" => "product",
        //         "name_en" => "box",
        //         "name_th" => "กล่อง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 2,
        //         "code" => "piece",
        //         "type" => "product",
        //         "name_en" => "piece",
        //         "name_th" => "ชิ้น",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 3,
        //         "code" => "stick",
        //         "type" => "product",
        //         "name_en" => "stick",
        //         "name_th" => "แท่ง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 4,
        //         "code" => "box",
        //         "type" => "product",
        //         "name_en" => "box",
        //         "name_th" => "ลัง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 5,
        //         "code" => "machine",
        //         "type" => "product",
        //         "name_en" => "machine",
        //         "name_th" => "เครื่อง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 6,
        //         "code" => "ea",
        //         "type" => "product",
        //         "name_en" => "ea",
        //         "name_th" => "อัน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 7,
        //         "code" => "dozen",
        //         "type" => "product",
        //         "name_en" => "dozen",
        //         "name_th" => "โหล",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 8,
        //         "code" => "pack",
        //         "type" => "product",
        //         "name_en" => "pack",
        //         "name_th" => "แพ็ค",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 9,
        //         "code" => "reel",
        //         "type" => "product",
        //         "name_en" => "reel",
        //         "name_th" => "ม้วน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 10,
        //         "code" => "case",
        //         "type" => "product",
        //         "name_en" => "case",
        //         "name_th" => "ตลับ",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 11,
        //         "code" => "inkwell",
        //         "type" => "product",
        //         "name_en" => "inkwell",
        //         "name_th" => "ขวด",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 12,
        //         "code" => "line",
        //         "type" => "product",
        //         "name_en" => "line",
        //         "name_th" => "เส้น",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 13,
        //         "code" => "set",
        //         "type" => "product",
        //         "name_en" => "set",
        //         "name_th" => "ชุด",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 14,
        //         "code" => "times",
        //         "type" => "service",
        //         "name_en" => "times",
        //         "name_th" => "ครั้ง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 15,
        //         "code" => "course",
        //         "type" => "service",
        //         "name_en" => "course",
        //         "name_th" => "คอร์ส",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 16,
        //         "code" => "person",
        //         "type" => "service",
        //         "name_en" => "person",
        //         "name_th" => "คน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 17,
        //         "code" => "man-day",
        //         "type" => "service",
        //         "name_en" => "man-day",
        //         "name_th" => "คน-วัน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 18,
        //         "code" => "man-month",
        //         "type" => "service",
        //         "name_en" => "man-month",
        //         "name_th" => "คน-เดือน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 19,
        //         "code" => "year",
        //         "type" => "service",
        //         "name_en" => "year",
        //         "name_th" => "ปี",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 20,
        //         "code" => "month",
        //         "type" => "service",
        //         "name_en" => "month",
        //         "name_th" => "เดือน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 21,
        //         "code" => "week",
        //         "type" => "service",
        //         "name_en" => "week",
        //         "name_th" => "สัปดาห์",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 22,
        //         "code" => "day",
        //         "type" => "service",
        //         "name_en" => "day",
        //         "name_th" => "วัน",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 23,
        //         "code" => "hour",
        //         "type" => "service",
        //         "name_en" => "hour",
        //         "name_th" => "ชั่วโมง",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 24,
        //         "code" => "minute",
        //         "type" => "service",
        //         "name_en" => "minute",
        //         "name_th" => "นาที",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ],
        //     [
        //         "id" => 25,
        //         "code" => "round",
        //         "type" => "service",
        //         "name_en" => "round",
        //         "name_th" => "รอบ",
        //         "is_active" => 1,
        //         "created_by" => "s",
        //         "updated_by" => null,
        //     ]
        // ];

        // if (count($units) > 0) {
        //     foreach ($units as $unit) {
        //         $unit['created_at'] = Carbon::now();
        //         $unit['updated_at'] = Carbon::now();
        //         Unit::create($unit);
        //     }
        // }

        $taxes = [
            [
                'code' => 'NON',
                'name_en' => 'NON VAT',
                'name_th' => 'ไม่มี VAT',
                'is_include' => false,
                'rate' => 0,
                'input_account_id' => null,
                'output_account_id' => 27,
                'paid_input_account_id' => null,
                'paid_output_account_id' => 26,
                'sequence' => 1,
            ],
            [
                'code' => 'ZER',
                'name_en' => 'VAT 0%',
                'name_th' => 'VAT 0%',
                'is_include' => false,
                'rate' => 0,
                'input_account_id' => null,
                'output_account_id' => 27,
                'paid_input_account_id' => null,
                'paid_output_account_id' => 26,
                'sequence' => 2,
            ],
            [
                'code' => 'STD',
                'name_en' => 'VAT 7%',
                'name_th' => 'VAT 7%',
                'is_include' => false,
                'rate' => 7,
                'input_account_id' => null,
                'output_account_id' => 27,
                'paid_input_account_id' => null,
                'paid_output_account_id' => 26,
                'sequence' => 3,
            ],
        ];
        if (count($taxes) > 0) {
            foreach ($taxes as $tax) {
                $tax['is_active'] = true;
                $tax['created_by'] = 's';
                $tax['updated_by'] = 's';
                $tax['created_at'] = Carbon::now();
                $tax['updated_at'] = Carbon::now();
                Tax::create($tax);
            }
        }
    }
}
